### ISSUE TITLE
Encoding data with multiple-of-3 length fails to write last 4 output bytes

### ISSUE THREAD

**Issue by sircfenner** [Reselim/Base64#2]
For example, encoding `Hello, world` (12 bytes):
- Expected (bytes, hex): `53 47 56 73 62 47 38 73 49 48 64 76 63 6d 78 6b`
- Actual (bytes, as hex): `53 47 56 73 62 47 38 73 49 48 64 76 00 00 00 00`

Decoding the malformed data above will cause a runtime error.

After allocating a correct-length array of 0 bytes here:
https://github.com/Reselim/Base64/blob/1d13d19ef651329543694d088a3d925458a3540e/Base64.lua#L40

When handling the multiple-of-three length case, it looks like the loop ends one index too early so the final bytes are not written:
https://github.com/Reselim/Base64/blob/1d13d19ef651329543694d088a3d925458a3540e/Base64.lua#L42

Should this be `... -1` rather than `... - (1 + 1)` ?

**Comment by Reselim** [comment]
Thanks for the heads up -- no clue how I hadn't spotted this.
